export const initialPosts = [
  {
    id: '1',
    title: 'ansar',
    text: 'serikbayev',
    createdAt: new Date('2024-03-22').toISOString(),
    voteCount: 394,
  },
  {
    id: '2',
    title: 'cristiano',
    text: 'ronaldo',
    createdAt: new Date('2024-02-15').toISOString(),
    voteCount: 187,
  },
  {
    id: '3',
    title: 'ansar',
    imageUrls: [
      'https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg',
    ],
    createdAt: new Date('2024-05-29').toISOString(),
    voteCount: 158,
  },
  {
    id: '4',
    title: "Google's New AI",
    text: 'Google has announced a new AI model that is expected to revolutionize the tech industry.',
    createdAt: new Date('2024-04-10').toISOString(),
    voteCount: 199,
  },
  {
    id: '5',
    title: 'Mount Everest',
    imageUrls: [
      'https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg',
    ],
    createdAt: new Date('2024-05-05').toISOString(),
    voteCount: 447,
  },
  {
    id: '6',
    title: 'Interesting Blog Post',
    linkUrl: 'https://example.com/blog/interesting-post',
    createdAt: new Date('2024-03-12').toISOString(),
    voteCount: 234,
  },
  {
    id: '7',
    title: "Tesla's New Car Model",
    text: 'Tesla has just unveiled its new electric car model which features advanced autonomous driving capabilities.',
    createdAt: new Date('2024-01-20').toISOString(),
    voteCount: 141,
  },
  {
    id: '8',
    title: 'Amazing Sunset',
    imageUrls: ['https://cdn.pixabay.com/photo/2023/10/21/11/46/sunset-8331285_640.jpg'],
    createdAt: new Date('2024-05-30').toISOString(),
    voteCount: 118,
  },
  {
    id: '9',
    title: 'Learn TypeScript',
    linkUrl: 'https://www.typescriptlang.org/',
    createdAt: new Date('2024-03-18').toISOString(),
    voteCount: 719,
  },
  {
    id: '10',
    title: 'Beach Vacation',
    text: 'Planning a vacation to the beach this summer. Any recommendations for the best spots?',
    createdAt: new Date('2024-06-01').toISOString(),
    voteCount: 279,
  },
  {
    id: '11',
    title: 'New York City',
    text: 'The city that never sleeps!',
    createdAt: new Date('2024-05-25').toISOString(),
    voteCount: 43,
  },
  {
    id: '12',
    title: 'JavaScript Tips',
    text: 'Here are some cool tips to write better JavaScript code.',
    createdAt: new Date('2024-02-20').toISOString(),
    voteCount: 325,
  },
  {
    id: '13',
    title: 'Healthy Eating',
    text: 'A guide to healthy eating habits.',
    createdAt: new Date('2024-03-15').toISOString(),
    voteCount: 639,
  },
  {
    id: '14',
    title: 'Space Exploration',
    text: 'The future of space exploration looks bright with new technologies.',
    createdAt: new Date('2024-04-22').toISOString(),
    voteCount: 167,
  },
  {
    id: '15',
    title: 'Programming Languages',
    text: 'Which programming language should you learn in 2024?',
    createdAt: new Date('2024-01-10').toISOString(),
    voteCount: 142,
  },
  {
    id: '16',
    title: 'Art in the Modern World',
    imageUrls: ['https://cdn.pixabay.com/photo/2023/10/21/11/46/sunset-8331285_640.jpg'],
    createdAt: new Date('2024-05-20').toISOString(),
    voteCount: 957,
  },
  {
    id: '17',
    title: 'Top 10 Beaches',
    text: 'Here are the top 10 beaches to visit this summer.',
    createdAt: new Date('2024-06-02').toISOString(),
    voteCount: 965,
  },
  {
    id: '18',
    title: 'World Cuisine',
    text: 'Explore the diverse and rich world of global cuisine.',
    createdAt: new Date('2024-02-14').toISOString(),
    voteCount: 222,
  },
  {
    id: '19',
    title: 'Fitness Tips',
    text: 'Stay fit and healthy with these tips.',
    createdAt: new Date('2024-03-25').toISOString(),
    voteCount: 756,
  },
  {
    id: '20',
    title: 'Travel Guide',
    text: 'Your guide to traveling around the world on a budget.',
    createdAt: new Date('2024-04-15').toISOString(),
    voteCount: 613,
  },
  {
    id: '21',
    title: 'Music Festivals',
    text: 'The best music festivals to attend this year.',
    createdAt: new Date('2024-05-10').toISOString(),
    voteCount: 487,
  },
  {
    id: '22',
    title: 'Photography Tips',
    imageUrls: [
      'https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg',
    ],
    createdAt: new Date('2024-05-12').toISOString(),
    voteCount: 94,
  },
  {
    id: '23',
    title: 'Cooking Recipes',
    text: 'Delicious recipes to try at home.',
    createdAt: new Date('2024-02-10').toISOString(),
    voteCount: 247,
  },
  {
    id: '24',
    title: 'Gaming News',
    text: 'The latest news in the gaming world.',
    createdAt: new Date('2024-03-28').toISOString(),
    voteCount: 177,
  },
  {
    id: '25',
    title: 'Book Recommendations',
    text: 'Must-read books for 2024.',
    createdAt: new Date('2024-01-25').toISOString(),
    voteCount: 214,
  },
  {
    id: '26',
    title: 'Tech Gadgets',
    text: 'The coolest tech gadgets to look out for.',
    createdAt: new Date('2024-04-05').toISOString(),
    voteCount: 328,
  },
  {
    id: '27',
    title: 'Movie Reviews',
    text: 'The best movies of 2024 reviewed.',
    createdAt: new Date('2024-05-01').toISOString(),
    voteCount: 849,
  },
  {
    id: '28',
    title: 'Fitness Challenges',
    text: 'Take on these fitness challenges to stay in shape.',
    createdAt: new Date('2024-03-10').toISOString(),
    voteCount: 850,
  },
  {
    id: '29',
    title: 'Gardening Tips',
    text: 'Grow your own garden with these tips.',
    createdAt: new Date('2024-06-01').toISOString(),
    voteCount: 145,
  },
  {
    id: '30',
    title: 'Work-Life Balance',
    text: 'Tips to maintain a healthy work-life balance.',
    createdAt: new Date('2024-02-01').toISOString(),
    voteCount: 239,
  },
];
